INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','BRIAN 3140',' ','','','','','','','10.10.4.129','7','','BODEGA TICS PISO 4','SIN USO  ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('GENERICO','','PS/2020/008','','windows 10','OFFICE 2016','AMD E1 21.4 Ghz','4','1000','10.10.4.116','7','','"NO SE CAMBIO LA CONTRASEÑA
JESÚS GONZALEZ"','CELENE CABALLERO RAMÍREZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','DC7900','MXJ84909XB',' PSTIC-CGPS-123','windows 7','"OFFICE2010
2GRAM"','CORE 2 DUO  2.0 Ghz','2','160','10.10.4.119','7','','','JESUS GONZALEZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','BRIAN 3140','711456012','PSTIC-CGPS-ST-109','windows 7','"OFFICE2010
"','1.8 Ghz','2','160','10.10.4.113','7','','','VLADIMIR AGUILAR GARCIA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','OPTIPLEX','G6FBYH1','PSTIC-CGPS-ST-108','windows 7','OFFICE 2010','CORE 2 DUO  2.0 Ghz','2','160','10.10.4.123','7','','','ISABEL PRIMERO ARRIAGA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LENOVO','11EE-S0D200','YL01AKGG','','','','Intel i7 2.9Ghz','16','1500','10.10.4.127','7','personal','','PAOLA FATIMA GARCÍA MARQUEZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205 G3 AIO BUSINES PC','8CC74804JS','','windows 10','OFFICE 2019','Intel Celeron 2.4Ghz','4','1000','10.10.4.114','7','','','GLORIA RUBI VELAZQUEZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205 G3 AIO BUSINES PC','8CC81003KM','','windows 10','OFFICE 2016','Intel Celeron 2.4Ghz','4','1000','10.10.4.115','7','','','KARLA JIMENEZ TORRES');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205 G3 AIO BUSINES PC','8CC74804LZ','','windows 10','OFFICE 2010','Intel Celeron 2.4Ghz','4','1000','10.10.4.117','7','','','MARIA RAQUEL GARCIA FLORES');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','7V63K','J43ZZS2','','windows 10','OFFICE 2016','Intel i5 1.8Ghz','4','1000','10.10.4.121','7','','','CARLOS DIAZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('','','','','','','','','','10.10.4.122','7','personal','EQUIPO PERSONAL IP PRESTADA','ARTURO CERVANTES ESTRADA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL ','VGS14KBL','8TP51P2','','','','Intel i5','4','1000','','7','','','VLADIMIR AGUILAR GARCIA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL ','VGS14KBL','78ZVWN2','','','','','','','','7','','','VLADIMIR AGUILAR GARCIA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','7V63K','3QKYZS2','','','','','','','10.10.4.126','7','','','OSCAR ADRIAN RAMIREZ TELLEZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('ACTECK','ACG-8010','"119264031220
 "','PSTIC-CGA-JUDTIC-212','','','Core DUO 1.8Ghz','1','80','','7','','BODEGA TICS 4 PISO','ARTURO CERVANTES  (SIN USO OFICINA DE RAQUEL)');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('GENERICO','','S/N (940233148975)','PSTIC-CGPS-ST-115','windows 10','OFFICE 2016','Intel Celeron 2.4Ghz','8','500','10.10.4.107','7','','','CLAUDIA I. ESPINDOLA ESPINOSA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('GENERICO','SKOOZ','DAF2011012','PSTIC-CGPS-ST-117','','','Intel Celeron 2.4Ghz','4','1000','10.10.4.120','7','','','HÉCTOR FUENTES JUÁREZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','BRIAN 3140','"711456029
"','PSTIC-CGPS-ST-118','','','Core 2 DUO 2.3Ghz','2','160','10.10.4.118','7','','SIN CONEXIÓN','HÉCTOR FUENTES JUÁREZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','BRIAN ','"711456034
"','PSTIC-CGPS-ST-119','','','Core 2 DUO 2.3Ghz','2','160','10.10.4.125','7','','','VARIOS USUARIOS (MIGUEL)');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('GENERICO','','','PSTIC-CGA-JUDTIC-215','','','Intel Celeron 2.4Ghz','4','1000','10.10.4.97','7','','"SALE POR
10.10.7.200"','MARIA CRUZ PLATA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','7V63K','3NHWZS2','','windows 10','OFFICE 2016','','4','1000','10.10.4.104','7','','','SERVICIO');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','7V63K','3MP20T2','','','','Intel i5','4','1000','','7','','SIN USO OFIINADE ARQ. ALEJANDRO','ARQ. ALEJANDRO AGUSTIN ROJAS HERRERA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','7V63K','3NNWZS2','','','','Intel i5 2.0Ghz','4','1000','','7','','','EFRAIN RAMOS GARCIA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('','','','','','','','','','10.10.4.99','7','personal','LAPTOP PERSONAL','LAPTOP PERSONAL');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('','','','','','','','','','10.10.4.106','7','personal','LAPTOP PERSONAL','LAPTOP PERSONAL');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('','','','','','','','','','10.10.6.40','7','','','');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','BRIAN 3140','"711456005
"','PSTIC-CGPS-ST-105','','','','','','10.10.4.124','7','','BODEGA TICS 4 PISO','JUAN DIAZ CRUZ CHECAR ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','OPTIPLEX 755','"F0X18F1
 "','PSTIC-CGPS-ST-106','','','','','','10.10.4.102','7','','BODEGA TICS 4 PISO','ISAIAS AYALA BRITO');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','7V63K','J2P00T2','','windows 10','OFFICE 2016','Intel i5','4','1000','10.10.4.98','7','','SIN CONEXIÓN','PAOLA FATIMA GARCÍA MARQUEZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','TITAN 4040','"811568111
"','PSTIC-CGPS-ST-110','','','','','','10.10.4.100','7','','EN BODEGA TICS 4TO. PISO','IVAN PINEDA PINEDA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','DC7900','"MXJ8450CV7
"','PSTIC-CGPS-ST-111','windows 7','OFFICE2010','','','','10.10.4.105','7','','EN BODEGA TICS 4TO. PISO','FERNANDO ESTRADA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','BRAIN 3140','711456027','PSTIC-CGPS-ST-113','windows 7','OFFICE2010','Core 2 DUO 1.8Ghz','1','500','10.10.4.103','7','','','ENRIQUE PEDRAZA VIDAL');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('GENERICO','','S/N (940233144387)','PSTIC-CGPS-ST-114','windows 7','OFFICE 2007','Intel Celeron 2.4Ghz','8GRAM','500','10.10.4.108','7','','','JENIFER BEATRIZ PÉREZ TORIBIO');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205 G3 AIO BUSINESS PC','8CC8201GGQ','','','','','4','1000','','7','','','KENIA RIVERA HERNANDEZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205 G3 AIO BUSINES PC','8CC80912G0','','','','','4','1000','','7','','SIN USO EN OFICIA DE ARQ. ALEJANDRO','ARQ. ALEJANDRO AGUSTIN ROJAS HERRERA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','7V63K','2MTGZT2','','windows 10','OFFICE 2019','Intel i5 2.0Ghz','4','1000','10.10.4.109','7','','SALE POR DHCP','NORMA GARCÍA LÓPEZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('','','20050003218','','','','','','','10.10.4.101','7','personal','PERSONAL','JUAN PABLO JULIAN ARCOS');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','BRIAN 3140','711456016','PSTIC-OPS-168','Windows 7','Office 2010','Intel Core 2 DUO 18.Ghz','1','160','10.10.5.51','1','','','MARIA TERESA RAMÍREZ CORTES');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205 G3 AIO BUSINES PC','8CC81003HL','','Windows 10','Office 2019','Intel Core i5 2.8Ghz','4','1000','10.10.5.91','1','','','ALEJANDRO LARA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','TITAN 4040','903627513','PSTIC-OPS-169','Windows 10','Office 2019','Intel Celeron 2.0Ghz','4','230','10.10.5.52','1','','','NORMA ANGELICA NAVA SANDOVAL');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','TITAN 4040','905659710','PSTIC-UT-189','Windows 7','Office 2007','Intel Atom 1.6Ghz','2','80','10.10.5.53','1','','','MARISOL VERA GARRIDO');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205  G3 AIO  BUSINESS PC','8CC80912FS','','Windows 10','Office 2019','Intel Core i5 2.8Ghz','4','1000','10.10.5.54','1','','','MARIA ELIZABETH MARTINEZ SANCHEZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205  G3 AIO  BUSINESS PC','8CC74804N3','','Windows 10','Office 2019','Intel Core i5 2.8Ghz','4','1000','10.10.5.55','1','','','ERIKA VIRIDIA GARCÍA PÉREZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('GENERICO','','','','','','','','','10.10.5.161','1','','','LIZBETH ESPINOSA DE LOS MONTEROS HERNÁNDEZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LENOVO','','','PSTIC-CGA-JUDTIC-203','','','','','','10.10.5.56','1','','','LIZBETH EVANGELINA ESPINOSA DE LOS MONTEROS');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205  G3 AIO  BUSINESS PC','8CC8210G47','','Windows 10','Office 2019','Intel Core i5 2.8Ghz','4','1000','10.10.5.60','1','','TRABAJO EN CASA','LIZBETH EVANGELINA ESPINOSA DE LOS MONTEROS');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LANIX','BRIAN 3140','711456003','','Windows 7','Office 2010','Intel Core 2 DUO 1.8Ghz','1','160','','1','','LA DARA DE BAJA SIN USAR','LIZBETH ESPINOSA DE LOS MONTEROS HERNÁNDEZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205 G3 AIO BUSINES PC','8CC8210G00','','Windows 10','Office 2019','Intel Core i5 2.8Ghz','4','1000','" 10.10.5.58 
10.10.5.50    "','1','','"MODEM 
TIENE ACTUALMENTE LA 10.10.5.50
SE ASIGAN IP EN CASO DE OCUPAR CABLE"','LESLYE VICENTE AMPARAN');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('H.P.','DC7900','MXJ84909XF','PSTIC-UT-187','Windows 7','Office 2010','Intel Core 2 DUO 2.6Ghz','1','250','10.10.5.59','1','','','ANDREA GONZALEZ CORNEJO');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','OPTIPLEX 755','35KJFG1','PSTIC-UT-193','Windows 7','Office 2010','Intel Core 2 DUO 2.3Ghz','2','160','10.10.5.61','1','','','ANDREA GONZALEZ CORNEJO');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LENOVO','IDEACENTRE 300S-11IBR','R302XUXB','PSTIC-UT-190','Windows 7','Office 2010','Intel Celeron 1.6Ghz','8','500','10.10.5.62','1','','AMPLIAR MEMORIA','SARAI RAMÍREZ BAUTISTA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LENOVO','','R302XUVC','PSTIC-JUDTIC-204','Windows 7','Office 2010','Intel Celeron 1.6Ghz','4','500','10.10.5.63','1','','NO HAY CONEXION','DAVID GUZMAN CORROVIÑA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','7V63K','J2JZZS2','','Windows 10','Office 2019','Intel Core i5 2.8Ghz','4','1000','10.10.5.64','1','','OFICINA CERRADA SE ASIGNA IP','DAVID GUZMAN CORROVIÑA');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','205  G3 AIO  BUSINESS PC','8CC8201GFZ','','Windows 10','Office 2019','Intel Core i5 2.8Ghz','4','1000','10.10.5.11','1','','','YERICA ANTONIETA COPCA GUTIÉRREZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('GENERICO','','','PSTIC-CGA-ACH-126','','','','','','10.10.5.12','1','','','YERICA ANTONIETA COPCA GUTIÉRREZ');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','D530CMT','MXJ41901HP','PSTIC-OPS-170','','','','','','','1','','SE ENCUENTRA EN TICS','MARIA TERESA RAMIREZ CORTES');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','VGS14KBL','92K7YF3','','Windows 10','Office 2019','AMD RYZEN 2.8Ghz','8','250','10.10.5.190','1','','','PROCURADORA SOCIAL');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('HP','SMART','CN1BC3908M','','','','','','','INSTALACION LOCAL','1','','','LESLYE VICENTE AMPARAN');
INSERT INTO `inventario_cpus`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `software_so`, `software_office_version`, `hardware_procesador`, `hardware_ram_gb`, `hardware_disco_capacidad_gb`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('DELL','','F5ZVWN2','','','','','','','10.10.5.57','1','','SECRETARIA PARTICULAR','ERICA HERNANDEZ FIGUEROA');
INSERT INTO `inventario_impresoras`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LEXMARK','MX611DHE','70167GHH0D880','','10.10.0.8','1','','','');
INSERT INTO `inventario_impresoras`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LEXMARK','MS810de','40638D660170F','','10.10.7.55','1','','','');
INSERT INTO `inventario_impresoras`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LEXMARK','MS810de','40638D66019GT','','INSTALACION LOCAL','1','','','');
INSERT INTO `inventario_impresoras`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('KYOCERA','','','','10.10.6.10','1','','','');
INSERT INTO `inventario_impresoras`(`id_marca`, `id_modelo`, `id_no_serie`, `id_no_control_interno`, `internet_ip`, `control_id_area`, `obs_tipo_adquisicion`, `obs_status`, `referencia`) VALUES ('LEXMARK','MX611JHE','70167GHH0D9VT','','10.10.6.111','1','','','');